name: Deploy to Server

on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e  # Exit on any error

            echo "Starting deployment..."

            # Navigate to project directory
            cd jubilant-octo-rotary-phone

            # Ensure we're on master branch and pull latest changes
            echo "Checking out master branch..."
            git checkout master

            echo "Pulling latest changes..."
            git pull origin master

            # Remove 'draft: true' from any articles in content/posts/*.md
            echo "Removing draft status from posts..."
            find content/posts/ -name "*.md" -type f \
              -exec sed -i \
              '/^[[:space:]]*draft[[:space:]]*=[[:space:]]*true[[:space:]]*$/d' {} \; || true

            # Build the site with Hugo
            echo "Building site with Hugo..."
            hugo

            echo "Deployment completed successfully!"
